version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${ROOT_FOLDER}
      - MYSQL_PASSWORD=password
  php:
    build:
      context: php
      args:
        - ROOT_FOLDER=${ROOT_FOLDER}
    ports: ['9000:9000']
    volumes: ['..//:/var/www/${ROOT_FOLDER}:cached']
    links:
      - mysql:mysql
    depends_on:
      - mysql
  nginx:
    build:
      context: nginx
      args:
        - ROOT_FOLDER=${ROOT_FOLDER}
    ports: ['80:80']
    volumes: ['..//:/var/www/${ROOT_FOLDER}:cached']
